FROM golang:alpine AS builder

WORKDIR /go/src/app
COPY go.mod .
COPY go.sum* .
RUN go mod download
COPY . .
{{ if .JSVMAssets }}RUN mkdir -p pb_migrations pb_hooks
{{ end }}RUN CGO_ENABLED={{.CgoEnabled}} go build -o pocketbase .

FROM debian:trixie-slim

RUN apt update && apt install --no-install-recommends \
    -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/src/app/pocketbase /
{{ if .JSVMAssets }}COPY --from=builder /go/src/app/pb_migrations /pb_migrations
COPY --from=builder /go/src/app/pb_hooks /pb_hooks
{{ end }}ENV PATH=$PATH:/

ENTRYPOINT ["/pocketbase"]
CMD ["serve", "--http", "0.0.0.0:8090"]
